package com.company;

public enum Token {
ASSIGNMENT,COMPARISON,GREATER,GREATER_EQUAL,
    LOWER,LOWER_EQUAL,NOT_EQUAL,MINUS,PLUS,PLUS_PLUS,
    MINUS_MINUS,CASE,PRODUCTION,REMAINED,LOGICAL_AND,LOGICAL_OR,
    DEVISION, FOR,WHILE,IF,ELSE,THEN,SWITCH,DOUBLE_TYPE,
    FLOAT_TYPE,LEFT_PARENTHESIS,RIGHT_PARENTHESIS,BREAK,ELSE_IF,
    ELSEIF,STATIC,VOID,PUBLIC,DEFAULT,CONTINUE,RETURN,LONG_TYPE,
    INT_TYPE, STRING_TYPE,CHAR_TYPE,BOOLEAN_TYPE,LEFTCURLY,
    RIGHTCURLY,LEFTSQ,RIGHTSQ,NULL,INTEGER,TRUE, FALSE,IDENTICAL,
    SEMICOLON,INTEGER_NUMBER,FLOAT_NUMBER,Comment,String_value,Char_value
}
